[bitcoin]
== 比特币

在人类历史的长河中，贵金属在很长的一段时间处于货币的地位，因为其稀缺性，保证了货币的相对稳定。纸币出现后，也在很长的时间段里，采用金本位制度，每单位的货币价值等同于若干重量的黄金。但是随着布雷顿森林货币体系的垮台，货币与黄金完全脱离了关系，所以通货膨胀了成为了货币的常态，货币成为了政府盘剥人民的工具。当规定货币数量上限的比特币出现后，许多理想主义者看到了希望，所以积极的投入到加密货币这场革命当中，当然也有许多投机者加入其中。

还有许多人从比特币的去中心架构中受到启发，尝试将这种思想应用到其他领域，去构建一个更加开放，更加平等的社会。因此，我们从比特币入手，先去了解一个去中心系统应该考虑的问题。

=== 比特币有何用？

比特币给人的第一感觉，未必是那么让人心动。例如，需要10分钟才能完成一笔比特币转账，而现在的大多数网银，几秒钟就可以完成一笔转账。不过场景稍微变化一下就会有不一样的体验，例如，诚诚要给美国的朋友希希转10万美元，通过传统网银可能会遇到一些困难，原因至少有两个：首先是政府监管，中国是外汇管制的国家，转这么多钱是会受到管控的；其次，也是最重要的，是协调中心。在中国有人民银行这类组织在扮演这种角色。在法律层面，人民银行作为央行，有政府为其背书，能够制订和推行各个银行与央行通讯的标准和规范，并强制推行。在实际业务层面，各个银行在人民银行有账户并保持一定余额，当发生跨行转账时，人民银行会在不同的银行账户之间记录转移金额，并定时与各个银行实现清算结算。从而实现国内的跨行转账。

各国都有类似的中央协调机构，但是在国际金融领域问题就会复杂许多，尽管有一些大银行尝试在国际上扮演这种中介的角色，但是困难重重。法律上，可能要应对政府的监管，例如中国这种有外汇管制的国家，不会允许一个不可控的银行执行这类业务；在执行上，很难涵盖世界上所有的银行。像SWIFT这种组织，也只能把自己的服务局限在消息传输网络和协议层面，无法在国际市场上达到银联和人民银行在中国国内的地位。此时，你可以发现比特币的优势了，给国内的朋友转比特币和给国外的朋友转，并没有任何区别，10十分钟大概就能完成。

这样看来，比特币确实能够实现一些传统金融机构无法完成的事情。比特币是如何做到的？是因为找到了一个不会被政府监管的协调中心了吗？不，即使有这样的中心，难道这个中心本身就一定信得过吗？不会被某个政府一网打尽吗？所以比特币是通过一个去中心化的系统完成了这些事情。

=== 比特币如何发挥作用

下面我们看看比特币是构建了怎样的去中心化系统，具备了传统银行无法实现的能力。

==== 去中心的网络

比特币之前最有名的去中心系统恐怕就是使用P2P协议的BT了。一个BT客户端启动后，会首先连接一些种子节点或者是之前连接过的节点，然后这些节点会给BT客户端发来一份可以连接的节点列表，BT客户端可以选择连接某些节点，然后与其交换缺失的数据，实现文件的下载。比特币使用了与BT类似的网络连接模式，在这种网络中，连接任何一个节点都一样，都能得到整个网络的数据，或者说去除掉网络中的任一主机，并不会丢失任何数据。实际上，比特币网络中的每个节点都有一份完整的账务信息，并且不断的与整个比特币网络保持同步。

但是比特币网络保存的数据和BT并不相同。BT传输的是某个文件的一部分，而比特币传输的转账交易记录，这造成了我们不能完全照搬BT的数据传输模式。我们看一个转账的场景，假设有个坏人东东，他的账户里有10个比特币，希希和贝贝各有一件他心仪的宝贝，都需要花费10个比特币购买，于是他连上比特币网络的某个节点A，支付了希希10个比特币；同时，又连上节点B，向贝贝支付了10个比特币。对于节点A和节点B，它们都看到东东的余额有10个比特币，可以执行这个交易，于是问题出现了，东东账户里只有10个比特币，这不就支付了两次？显然这种情况是不合理的。解决思路也很简单，保证在同一时间里，整个网络里只有一个节点记账，该节点记完帐之后，再把结果同步到其他节点。

[TIP]
====
做软件的朋友对此应该不会陌生，很多软件面临着选择主节点的问题。例如ZooKeeper、Etcd等服务注册软件。为了保持高可用性，这类软件都会同时启动不少于3个节点，其它软件访问其任一节点，都可以得到最新的配置信息。当需要修改配置时，这些运行的节点会运用诸如Raft这样的算法，自动选举出一个主节点，在该主节点完成配置的修改，然后将修改的结果同步到其他节点。比特币网络与此类网络是有很大差异的，首先比特币网络非常大，其中的节点不能知道整个网络上的所有节点；其次，ZooKeeper、Etcd网络中的节点都是互信的，Raft这类算法并不需要考虑其中有骗子的情况，只需要发挥协调作用就可以了，而比特币网络中的节点都是匿名的，无法信任的。因此，Raft之类算法的选举机制无法应用于比特币网络中。
====

==== 竞选主节点形成共识

所以，问题的关键是选举一个记账节点。对于互联和互信的网络来说，有很多简单的方法。举个例子，各个节点各自摇骰子，谁的号码最小谁做主。对于比特币网络来说，各个节点是匿名的，不可信的，节点可以谎报摇骰子的大小，而且各个节点并不能连接网络上的所有其他节点，所以也无法比较大小。因此，需要有一种无法作弊，且不需要和其他节点沟通的方法，于是就有了所谓的工作量证明（POW）算法。

整个比特币网络变成了一个竞选主节点，也就是记账节点的比赛。假定上一次是节点X完成了记账，X节点会留下一个谜题，这个谜题必须要做大量的计算才能得到答案。其他节点会通过比特币网络得到这个谜题，然后开始努力计算答案。我们假定是Y节点运气特别好，第一个得到了答案，它便成为这个周期的主节点，它负责记账，并把记账内容打成一个区块，附上下一次竞赛的谜题，分发给其他节点。其他节点可以验证Y完成了谜题，于是放弃自己的这一轮竞赛，接受Y提供的区块，并进入下一轮竞赛。

那如果有两个节点同时完成了谜题，会出现什么情况？首先，如果解题的耗时非常长，而且有相当大的随机性，那么这个同时得到答案的可能性就会很小。例如现在运行的比特币网络的解题时间大约是10分钟。其次，如果确实在世界上的不同地方，有两个节点Y1和Y2各自得到了答案，其他节点可以暂且搁置谁是谁非的判断，静待Y1和Y2的新出的谜题谁先被解答，先被解答的那个将会被最终确认，而另一个将会被搁置，最终抛弃。

[TIP]
====
对，这里已经出现了区块链的概念了。在比特币中，每一个区块都包含了对上一个区块的引用和相应谜题的答案，以及记账节点记录的转账信息。因为区块是一个个串起来的，所以我们称之为区块链。看到了没，我们使用区块，其实是被逼无奈，我们是多么希望用户提交交易后，立刻被整个比特币网络认可，但是要想形成共识，我们必须等待那个记账的主节点出现，如果谜题解密的时间过短，很容易出现冲突，解决共识冲突会更麻烦。当然，我们也不希望形成共识的时间过长，那样交易的确认也会需要更长的时间。此外，我们也应该看到，每个区块能够记录的交易可能有一定的限制，如果记录的交易太多，区块就会很大，在区块链P2P网络上的传输就会很慢，有些节点可能无法及时得到谜题，在竞赛中处于不利的地位。
====

==== 签名确定交易

这里先简单讲一点公钥密码学的基础。数学上会存在两个数字，私钥c和公钥d，二者存在这样的关系：一段文字x，经过d处理后得到d(x)，只能通过c解密c(d(x))=x，反之亦然，且没有算法可以通过d得到c。通常c会非常大，所以也很难通过反复测试得到c。

因为存在这样的技术，我们可以实现很多应用。首先是加密传输，例如诚诚可以把公钥d发给希希，然后希希用d加密自己的消息，发送回诚诚，诚诚用私钥c解密就能查看消息，传输公钥时诚诚和希希无需担心被窃取，因为公钥无法解密公钥加密的秘文。

另外一个广泛的应用就是数字签名，比如诚诚想给希希发一段信息x，但是他们担心有人会冒充诚诚发送信息，所以诚诚首先在公开网站公布自己的公钥d，希希记录下该公钥，然后诚诚向希希发送消息x以及经私钥处理过的秘文c(x)，即诚诚对于文本x的签名，希希得到x和c(x)后，即可通过d(c(x))是否为x判断该消息是否确实为诚诚所发。


==== 比特币的驱动力

=== 隐约的未来




