[bitcoin]
== 比特币有何用？

故事一定是从比特币开始。比特币给人的第一感觉，未必是那么让人心动。例如，需要10分钟才能完成一笔比特币转账，而现在的大多数网银，几秒钟就可以完成一笔转账。不过场景稍微变化一下就会有不一样的体验，例如，给你美国的一个朋友转10万美元，似乎传统网银都没有这样的能力，原因至少有两个：首先是政府监管，中国是外汇管制的国家，转这么多钱是会受到管控的；其次是协调中心，国际金融领域缺乏一个串联所有银行的中心机构，能够实现协调不同银行的转账业务，在中国有人民银行和银联这类组织在扮演这种角色。此时，你可以发现比特币的优势了，给国内的朋友转比特币和给国外的朋友转，并没有任何区别，10十分钟大概就能完成。

那我们看一下，我们否能打破这个壁垒，实现比特币一样的转账。政府监管和协调中心，这好像是同一个问题的两面。我们之所以敢于用网银转账，是我们相信银行不会骗我，而银行为何能得到这种信任，是因为其后有政府背书，政府的监管，保证其不会做出伤害我们的行为。首先，我们可以绕过政府监管吗？当然不能，各个国家都会有各种监管手段，只是监管的程度不同；那会有一个协调不同银行的中心吗？许多国家都有这样的机构，不过一旦涉及到国际业务，问题就会复杂许多，在一国内尚可以依靠政府强制推行规范和法律，推广到国际就会遇到难以调和的矛盾。例如SWIFT这种组织，无法在国际市场上达到银联和人民银行在中国国内的地位。

[TIP]
====
写到这里，我不禁哑然失笑，这是国人根深蒂固的思维模式啊。对于一个生活在中世纪欧洲的犹太人，时时处处都可能受到政府的打击，他们能相信的只有自己的联合体。对于非犹太人来说，只是程度稍微低一点罢了。虽然中世纪后欧洲国家的中央集权也不断加强，但还是没法和中国2000年的帝国史相比，在一个帝国的世界里，你的权益的最终解释权属于政府，不得不依赖，所以养成了国人对于政府的崇拜。
====

== 比特币如何发挥作用

我们再看比特币，为什么可以摆脱监管，无需中介即可实现货币的自由转移。

=== 去中心的网络

比特币之前最有名的去中心系统恐怕就是使用P2P协议的BT了。一个BT客户端启动后，会首先连接一些种子节点或者是之前连接过的节点，然后这些节点会给BT客户端发来一份可以连接的节点列表，BT客户端可以选择连接某些节点，然后与其交换缺失的数据，最后实现数据的同步。比特币使用了与BT类似的网络连接和数据同步模式，在这种情况下，连接任何一个节点都一样，都能得到整个网络的数据，或者说去除掉网络中的任一主机，并不会丢失任何数据。


--- 去中心如何形成共识
--- 如何保证共识是对的
--- 动力引擎是什么？
--- 


== 去中心化所面临的问题

=== 私密性
=== 共识
=== 驱动力


=== 为什么比特币可以成功？

=== 打开了一个崭新的世界

== 去中心化


