[preface]
== 序言

=== 关于本书

不知是因为常年的技术工作，还是纯粹的理性思维天性，对于任何新产生的事物，我都会思考它真的能工作吗？比特币和区块链来了，随之而来了许许多多的追风者。一方面，出了很多区块链的书，许多专家大讲特讲区块链的伟大，勾画了一副壮丽的场景，但我一直心存怀疑，不确定我们是否已经明确了未来之路？另一方面，又有许多实干家，似乎已经看清了道路，提出了许许多多区块链项目，但最后却变成发币，让人困惑，难道区块链就是发币？

IBM认为区块链的核心就是公共账本，于是Hyperledger Fabric项目的目标就变成了构建互信的私链。为了实现传统的企业安全需求，Fabric的运行架构变得过于复杂，但实际上却同时回避了很多可能性。而以太坊这类框架，却似乎有着非常单调的架构，是否并不适合构建企业级的私链？可能看了太多虚无缥缈的东西，起初，我对IBM关于区块链的理解，感到非常认同，但是复杂的架构和相对于以太坊似乎是不是有些自废武功，不过，这一切却使我不得不反思，这些区块链项目是解决的同一个问题吗？

比特币是人类的伟大发明，天然的稀缺性决定了它不会像法币一样不停的膨胀，政府无法像法币一样通过比特币暗自盘剥老百姓，正是抱着这种理想，许多人义无反顾地加入到了币圈。还有许多人，通过铸币的公平看到了更多的可能，所以又有了更多各式各样的区块链应用。我感觉，其中可能是有一个更高层次的问题，这个问题的答案也许不应该叫区块链，也许是对区块链的更深入的定义。

现在已经有了很多区块链相关的图书，我觉得其中一些偏理论，但脱离了实践，不免让人生疑；而另外一些讲的是技术细节，可能让我们忘记了为何会如此。我想尝试用通俗的语言描述道理，然后用实际的代码展示实现方式。为此，有了这本书。

=== 目标读者

我觉得这是一门入门书，虽然我是技术出身，但是我不是编程高手，估计没能力开发一个新的以太坊。但是，我应该可以通过研究各种技术所能做的事情来展示区块链？亦或者超越区块链？所以你如果不懂技术，也应该可以理解本书所讲的事情。如果你能懂一点开发，可以参考本书的内容，加深理解，甚至开始做一点事情。

=== 本书惯例

((("typographical conventions")))The following typographical conventions are used in this book:

_Italic_:: Indicates new terms, URLs, email addresses, filenames, and file extensions.

+Constant width+:: Used for program listings, as well as within paragraphs to refer to program elements such as variable or function names, databases, data types, environment variables, statements, and keywords.

**`Constant width bold`**:: Shows commands or other text that should be typed literally by the user.

_++Constant width italic++_:: Shows text that should be replaced with user-supplied values or by values determined by context.


[TIP]
====
This icon signifies a tip or suggestion.
====

[NOTE]
====
This icon signifies a general note.
====

[WARNING]
====
This icon indicates a warning or caution.
====

=== Code Examples

((("code examples, obtaining and using", id="codeuse00")))The examples are illustrated in Solidity, JavaScript and Python, and using the command line of a Unix-like operating system. All code snippets are available in the GitHub repository in the https://github.com/ethereumbook/ethereumbook/tree/first_edition/code[_code_] subdirectory of the main repository. Fork the book code, try the code examples, or submit corrections via GitHub:

https://github.com/ethereumbook/ethereumbook/tree/first_edition/

All the code snippets can be replicated on most operating systems with a minimal installation of compilers, interpreters and libraries for the corresponding languages. Where necessary, we provide basic installation instructions and step-by-step examples of the output of those instructions.

Some of the code snippets and code output have been reformatted for print. In all such cases, the lines have been split by a backslash (\) character, followed by a newline character. When transcribing the examples, remove those two characters and join the lines again and you should see identical results as shown in the example.

All the code snippets use real values and calculations where possible, so that you can build from example to example and see the same results in any code you write to calculate the same values. For example, the private keys and corresponding public keys and addresses are all real. The sample transactions, contracts, blocks, and blockchain references have all been introduced in the actual Ethereum blockchain and are part of the public ledger, so you can review them on any Ethereum system.

=== Using Code Examples

This book is here to help you get your job done. In general, if example code is offered with this book, you may use it in your programs and documentation. You do not need to contact us for permission unless you’re reproducing a significant portion of the code. For example, writing a program that uses several chunks of code from this book does not require permission. Selling or distributing a CD-ROM of examples from O’Reilly books does require permission. Answering a question by citing this book and quoting example code does not require permission. Incorporating a significant amount of example code from this book into your product’s documentation does require permission.

((("attribution")))We appreciate, but do not require, attribution. An attribution usually includes the title, author, publisher, and ISBN. For example: “_Mastering Ethereum_ by Andreas M. Antonopoulos (O’Reilly). Copyright 2018 Andreas M. Antonopoulos LLC,
978-1-491-97194-9.”

((("open source licenses")))Some editions of this book are offered under an open source license, such as https://creativecommons.org/licenses/by-nc/4.0/[CC-BY-NC], in which case the terms of that license apply.

If you feel your use of code examples falls outside fair use or the permission given above, feel free to contact us at pass:[<a href="mailto:permissions@oreilly.com">permissions@oreilly.com</a>].

=== Ethereum Addresses and Transactions in This Book

((("getting started", "warnings and cautions")))((("warnings and cautions", "avoid sending money to addresses appearing in book")))((("keys and addresses", "warnings and cautions")))((("transactions", "warnings and cautions")))((("blockchain applications", "warnings and cautions")))((("QR codes", "warnings and cautions")))The Ethereum addresses, transactions, keys, QR codes, and blockchain data used in this book are, for the most part, real. That means you can browse the blockchain, look at the transactions offered as examples, retrieve them with your own scripts or programs, etc.

However, note that the private keys used to construct addresses are either printed in this book, or have been "burned." That means that if you send money to any of these addresses, the money will either be lost forever, or in some cases everyone who can read the book can take it using the private keys printed in here.

[WARNING]
====
DO NOT SEND MONEY TO ANY OF THE ADDRESSES IN THIS BOOK. Your money will be taken by another reader, or lost forever.((("", startref="codeuse00")))
====

=== O'Reilly Safari

[role = "safarienabled"]
[NOTE]
====
pass:[<a href="http://oreilly.com/safari" class="orm:hideurl"><em class="hyperlink">Safari</em></a>] (formerly Safari Books Online) is a membership-based training and reference platform for enterprise, government, educators, and individuals.
====

Members have access to thousands of books, training videos, Learning Paths, interactive tutorials, and curated playlists from over 250 publishers, including O’Reilly Media, Harvard Business Review, Prentice Hall Professional, Addison-Wesley Professional, Microsoft Press, Sams, Que, Peachpit Press, Adobe, Focal Press, Cisco Press, John Wiley & Sons, Syngress, Morgan Kaufmann, IBM Redbooks, Packt, Adobe Press, FT Press, Apress, Manning, New Riders, McGraw-Hill, Jones & Bartlett, and Course Technology, among others.

For more information, please visit pass:[<a href="http://oreilly.com/safari" class="orm:hideurl"><em>http://oreilly.com/safari</em></a>].

=== How to Contact Us

((("comments and questions")))((("contact information")))Please address comments and questions concerning this book to the publisher:

++++
<ul class="simplelist">
  <li>O’Reilly Media, Inc.</li>
  <li>1005 Gravenstein Highway North</li>
  <li>Sebastopol, CA 95472</li>
  <li>800-998-9938 (in the United States or Canada)</li>
  <li>707-829-0515 (international or local)</li>
  <li>707-829-0104 (fax)</li>
</ul>
++++

To comment or ask technical questions about this book, send email to pass:[<a class="email" href="mailto:bookquestions@oreilly.com"><em>bookquestions@oreilly.com</em></a>].

For more information about our books, courses, conferences, and news, see our website at link:$$http://www.oreilly.com$$[].

Find us on Facebook: link:$$http://facebook.com/oreilly$$[]

Follow us on Twitter: link:$$http://twitter.com/oreillymedia$$[]

Watch us on YouTube: link:$$http://www.youtube.com/oreillymedia$$[]

=== Contacting the Author

You can contact me, Andreas M. Antonopoulos, on my personal site:
link:$$https://antonopoulos.com/$$[]

Information about "Mastering Ethereum" as well as the Open Edition and translations are available on:
link:$$https://ethereumbook.info/$$[]

Follow me on Facebook:
link:$$https://facebook.com/AndreasMAntonopoulos$$[]

Follow me on Twitter:
link:$$https://twitter.com/aantonop$$[]

Follow me on Linkedin:
link:$$https://linkedin.com/company/aantonop$$[]

Many thanks to all my patrons who support my work through monthly donations. You can follow my Patreon page here:
link:$$https://patreon.com/aantonop$$[]

=== Acknowledgments

I owe my love of words and books to my mother, Theresa, who raised me in a house with books lining every wall. My mother also bought me my first computer in 1982, despite being a self-described technophobe. My father, Menelaos, a civil engineer who just published his first book at 80 years old, was the one who taught me logical and analytical thinking and a love of science and engineering.

Thank you all for supporting me throughout this journey.

[[github_contrib]]
==== Early Release Draft (GitHub Contributions)

Many contributors offered comments, corrections, and additions to the early-release draft on GitHub. Thank you all for your contributions to this book.

Following is a list of notable GitHub contributors, including their GitHub ID in parentheses:

* Christopher Gondek (christophergondek)
* Javier Rojas (fjrojasgarcia)
* Jon Ramvi (ramvi)
* Kevin Carter (kcar1)
* Krzysztof Nowak (krzysztof)
* Liang Ma (liangma)
* Matthew Sedaghatfar (sedaghatfar)
* Mike Pumphrey (bmmpxf)
* Qiao Wang (qiaowang26)
* Will Binns (wbnns)
* Bryant Eisenbach (fubuloubu)
* Assaf Yossifoff (assafy)
* Nagesh Subrahmanyam (chainhead)
* Xavier Lavayssière (xalava)
* Vignesh Karthikeyan (meshugah)
* Adam Zaremba (zaremba)
* Steve Klise (sklise)
* Jonathan Velando (rigzba21)
* Pierre-Jean Subervie (pjsub)
* Martin Berger (drmartinberger)
* Jason Hill (denifednu)
* Diego H. Gurpegui (diegogurpegui)
* Zhen Wang (zmxv)
* Roger Häusermann (haurog)
* Joel Gugger (guggerjoel)
* Yash Bhutwala (yashbhutwala)
* Yeramin Santana (ysfdev)
* Nichanan Kesonpat (nichanank)
* Tim Nugent (timnugent)
* Pong Cheecharern (Pongch)
* Franco Daniel Berdun (fMercury)
* Cornell Blockchain (CornellBlockchain)
  - Brian Guo (BrianGuo)
  - Lucas Switzer (LucasSwitz)
  - Ohad Koronyo (ohadh123)
  - Giancarlo Pacenza (GPacenza)
  - Alex Frolov (sashafrolov)
  - Richard Sun (richardsfc)
  - Brian Leffew (bleffew99)
